version: '2'

services:
  telegraf:
    restart: always
    image: telegraf:latest
    volumes:
      - "./home/docker/mystack/telegraf.conf:/etc/telegraf/telegraf.conf:ro"

  influxdb:
    restart: always
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=password"
      - "INFLUXDB_DB=internet_speed_test"
    volumes:
      - "./data/influxdb/:/var/lib/influxdb"
